export const testResult = {
  bestResults: [
    {
      weaponLine: {
        slots: [
          36,
          97,
          112,
          124,
        ],
        elements: {
          Fire: 2,
          Mirage: 10,
          Wind: 4,
          Space: 6,
        },
        fulfilledShardSkills: [
          2,
          3,
          5,
          13,
          19,
        ],
      },
      shieldLine: {
        slots: [
          40,
          30,
          16,
          110,
        ],
        elements: {
          Fire: 4,
          Water: 13,
          Mirage: 6,
          Earth: 12,
        },
        fulfilledShardSkills: [
          30,
          34,
          35,
          36,
          46,
          50,
        ],
      },
      driveLine: {
        slots: [
          41,
          117,
          107,
          35,
        ],
        elements: {
          Fire: 6,
          Mirage: 8,
          Water: 7,
          Space: 14,
          Earth: 10,
        },
        fulfilledShardSkills: [
          57,
          58,
          63,
          68,
          69,
          73,
          80,
          83,
        ],
      },
      extraLine: {
        slots: [
          38,
          21,
          70,
        ],
        elements: {
          Fire: 6,
          Water: 2,
          Wind: 6,
          Space: 4,
        },
        fulfilledShardSkills: [
          86,
          87,
          89,
          103,
          108,
        ],
      },
    },
    {
      weaponLine: {
        slots: [
          36,
          97,
          112,
          124,
        ],
        elements: {
          Fire: 2,
          Mirage: 10,
          Wind: 4,
          Space: 6,
        },
        fulfilledShardSkills: [
          2,
          3,
          5,
          13,
          19,
        ],
      },
      shieldLine: {
        slots: [
          40,
          30,
          16,
          120,
        ],
        elements: {
          Fire: 4,
          Water: 13,
          Mirage: 5,
          Earth: 12,
        },
        fulfilledShardSkills: [
          30,
          34,
          35,
          36,
          46,
        ],
      },
      driveLine: {
        slots: [
          41,
          117,
          107,
          35,
        ],
        elements: {
          Fire: 6,
          Mirage: 8,
          Water: 7,
          Space: 14,
          Earth: 10,
        },
        fulfilledShardSkills: [
          57,
          58,
          63,
          68,
          69,
          73,
          80,
          83,
        ],
      },
      extraLine: {
        slots: [
          38,
          21,
          70,
        ],
        elements: {
          Fire: 6,
          Water: 2,
          Wind: 6,
          Space: 4,
        },
        fulfilledShardSkills: [
          86,
          87,
          89,
          103,
          108,
        ],
      },
    },
    {
      weaponLine: {
        slots: [
          36,
          97,
          112,
          124,
        ],
        elements: {
          Fire: 2,
          Mirage: 10,
          Wind: 4,
          Space: 6,
        },
        fulfilledShardSkills: [
          2,
          3,
          5,
          13,
          19,
        ],
      },
      shieldLine: {
        slots: [
          40,
          30,
          16,
          120,
        ],
        elements: {
          Fire: 4,
          Water: 13,
          Mirage: 5,
          Earth: 12,
        },
        fulfilledShardSkills: [
          30,
          34,
          35,
          36,
          46,
        ],
      },
      driveLine: {
        slots: [
          41,
          117,
          107,
          87,
        ],
        elements: {
          Fire: 9,
          Mirage: 3,
          Time: 5,
          Space: 14,
          Earth: 10,
        },
        fulfilledShardSkills: [
          60,
          62,
          63,
          65,
          68,
          73,
          74,
          83,
        ],
      },
      extraLine: {
        slots: [
          38,
          21,
          70,
        ],
        elements: {
          Fire: 6,
          Water: 2,
          Wind: 6,
          Space: 4,
        },
        fulfilledShardSkills: [
          86,
          87,
          89,
          103,
          108,
        ],
      },
    },
    {
      weaponLine: {
        slots: [
          36,
          97,
          112,
          124,
        ],
        elements: {
          Fire: 2,
          Mirage: 10,
          Wind: 4,
          Space: 6,
        },
        fulfilledShardSkills: [
          2,
          3,
          5,
          13,
          19,
        ],
      },
      shieldLine: {
        slots: [
          40,
          30,
          16,
          120,
        ],
        elements: {
          Fire: 4,
          Water: 13,
          Mirage: 5,
          Earth: 12,
        },
        fulfilledShardSkills: [
          30,
          34,
          35,
          36,
          46,
        ],
      },
      driveLine: {
        slots: [
          41,
          117,
          107,
          76,
        ],
        elements: {
          Fire: 6,
          Mirage: 3,
          Time: 4,
          Space: 14,
          Earth: 10,
        },
        fulfilledShardSkills: [
          58,
          60,
          62,
          63,
          68,
          73,
          74,
          83,
        ],
      },
      extraLine: {
        slots: [
          38,
          21,
          70,
        ],
        elements: {
          Fire: 6,
          Water: 2,
          Wind: 6,
          Space: 4,
        },
        fulfilledShardSkills: [
          86,
          87,
          89,
          103,
          108,
        ],
      },
    },
    {
      weaponLine: {
        slots: [
          26,
          97,
          112,
          124,
        ],
        elements: {
          Water: 5,
          Mirage: 10,
          Wind: 4,
          Space: 6,
        },
        fulfilledShardSkills: [
          1,
          3,
          5,
          13,
          19,
          20,
        ],
      },
      shieldLine: {
        slots: [
          40,
          30,
          16,
          120,
        ],
        elements: {
          Fire: 4,
          Water: 13,
          Mirage: 5,
          Earth: 12,
        },
        fulfilledShardSkills: [
          30,
          34,
          35,
          36,
          46,
        ],
      },
      driveLine: {
        slots: [
          41,
          117,
          107,
          76,
        ],
        elements: {
          Fire: 6,
          Mirage: 3,
          Time: 4,
          Space: 14,
          Earth: 10,
        },
        fulfilledShardSkills: [
          58,
          60,
          62,
          63,
          68,
          73,
          74,
          83,
        ],
      },
      extraLine: {
        slots: [
          38,
          21,
          70,
        ],
        elements: {
          Fire: 6,
          Water: 2,
          Wind: 6,
          Space: 4,
        },
        fulfilledShardSkills: [
          86,
          87,
          89,
          103,
          108,
        ],
      },
    },
    {
      weaponLine: {
        slots: [
          26,
          97,
          112,
          124,
        ],
        elements: {
          Water: 5,
          Mirage: 10,
          Wind: 4,
          Space: 6,
        },
        fulfilledShardSkills: [
          1,
          3,
          5,
          13,
          19,
          20,
        ],
      },
      shieldLine: {
        slots: [
          40,
          30,
          16,
          122,
        ],
        elements: {
          Fire: 4,
          Water: 16,
          Mirage: 5,
          Earth: 12,
        },
        fulfilledShardSkills: [
          30,
          34,
          35,
          36,
          46,
        ],
      },
      driveLine: {
        slots: [
          41,
          117,
          107,
          76,
        ],
        elements: {
          Fire: 6,
          Mirage: 3,
          Time: 4,
          Space: 14,
          Earth: 10,
        },
        fulfilledShardSkills: [
          58,
          60,
          62,
          63,
          68,
          73,
          74,
          83,
        ],
      },
      extraLine: {
        slots: [
          38,
          21,
          70,
        ],
        elements: {
          Fire: 6,
          Water: 2,
          Wind: 6,
          Space: 4,
        },
        fulfilledShardSkills: [
          86,
          87,
          89,
          103,
          108,
        ],
      },
    },
    {
      weaponLine: {
        slots: [
          75,
          97,
          112,
          124,
        ],
        elements: {
          Time: 2,
          Mirage: 10,
          Wind: 4,
          Space: 6,
        },
        fulfilledShardSkills: [
          3,
          4,
          5,
          13,
          19,
        ],
      },
      shieldLine: {
        slots: [
          40,
          30,
          16,
          122,
        ],
        elements: {
          Fire: 4,
          Water: 16,
          Mirage: 5,
          Earth: 12,
        },
        fulfilledShardSkills: [
          30,
          34,
          35,
          36,
          46,
        ],
      },
      driveLine: {
        slots: [
          41,
          117,
          107,
          76,
        ],
        elements: {
          Fire: 6,
          Mirage: 3,
          Time: 4,
          Space: 14,
          Earth: 10,
        },
        fulfilledShardSkills: [
          58,
          60,
          62,
          63,
          68,
          73,
          74,
          83,
        ],
      },
      extraLine: {
        slots: [
          38,
          21,
          70,
        ],
        elements: {
          Fire: 6,
          Water: 2,
          Wind: 6,
          Space: 4,
        },
        fulfilledShardSkills: [
          86,
          87,
          89,
          103,
          108,
        ],
      },
    },
    {
      weaponLine: {
        slots: [
          26,
          97,
          112,
          124,
        ],
        elements: {
          Water: 5,
          Mirage: 10,
          Wind: 4,
          Space: 6,
        },
        fulfilledShardSkills: [
          1,
          3,
          5,
          13,
          19,
          20,
        ],
      },
      shieldLine: {
        slots: [
          40,
          30,
          -1,
          122,
        ],
        elements: {
          Fire: 4,
          Water: 8,
          Mirage: 5,
        },
        fulfilledShardSkills: [
          30,
          34,
          36,
          46,
        ],
      },
      driveLine: {
        slots: [
          41,
          117,
          107,
          76,
        ],
        elements: {
          Fire: 6,
          Mirage: 3,
          Time: 4,
          Space: 14,
          Earth: 10,
        },
        fulfilledShardSkills: [
          58,
          60,
          62,
          63,
          68,
          73,
          74,
          83,
        ],
      },
      extraLine: {
        slots: [
          38,
          21,
          70,
        ],
        elements: {
          Fire: 6,
          Water: 2,
          Wind: 6,
          Space: 4,
        },
        fulfilledShardSkills: [
          86,
          87,
          89,
          103,
          108,
        ],
      },
    },
    {
      weaponLine: {
        slots: [
          26,
          97,
          112,
          124,
        ],
        elements: {
          Water: 5,
          Mirage: 10,
          Wind: 4,
          Space: 6,
        },
        fulfilledShardSkills: [
          1,
          3,
          5,
          13,
          19,
          20,
        ],
      },
      shieldLine: {
        slots: [
          40,
          30,
          -1,
          122,
        ],
        elements: {
          Fire: 4,
          Water: 8,
          Mirage: 5,
        },
        fulfilledShardSkills: [
          30,
          34,
          36,
          46,
        ],
      },
      driveLine: {
        slots: [
          41,
          117,
          107,
          73,
        ],
        elements: {
          Fire: 6,
          Mirage: 3,
          Time: 4,
          Space: 14,
          Earth: 10,
        },
        fulfilledShardSkills: [
          58,
          60,
          62,
          63,
          68,
          73,
          74,
          83,
        ],
      },
      extraLine: {
        slots: [
          38,
          21,
          70,
        ],
        elements: {
          Fire: 6,
          Water: 2,
          Wind: 6,
          Space: 4,
        },
        fulfilledShardSkills: [
          86,
          87,
          89,
          103,
          108,
        ],
      },
    },
    {
      weaponLine: {
        slots: [
          2,
          97,
          112,
          124,
        ],
        elements: {
          Earth: 6,
          Mirage: 10,
          Wind: 4,
          Space: 6,
        },
        fulfilledShardSkills: [
          0,
          3,
          5,
          13,
          19,
        ],
      },
      shieldLine: {
        slots: [
          40,
          30,
          -1,
          122,
        ],
        elements: {
          Fire: 4,
          Water: 8,
          Mirage: 5,
        },
        fulfilledShardSkills: [
          30,
          34,
          36,
          46,
        ],
      },
      driveLine: {
        slots: [
          41,
          117,
          107,
          73,
        ],
        elements: {
          Fire: 6,
          Mirage: 3,
          Time: 4,
          Space: 14,
          Earth: 10,
        },
        fulfilledShardSkills: [
          58,
          60,
          62,
          63,
          68,
          73,
          74,
          83,
        ],
      },
      extraLine: {
        slots: [
          38,
          21,
          70,
        ],
        elements: {
          Fire: 6,
          Water: 2,
          Wind: 6,
          Space: 4,
        },
        fulfilledShardSkills: [
          86,
          87,
          89,
          103,
          108,
        ],
      },
    },
    {
      weaponLine: {
        slots: [
          2,
          97,
          112,
          124,
        ],
        elements: {
          Earth: 6,
          Mirage: 10,
          Wind: 4,
          Space: 6,
        },
        fulfilledShardSkills: [
          0,
          3,
          5,
          13,
          19,
        ],
      },
      shieldLine: {
        slots: [
          40,
          30,
          -1,
          122,
        ],
        elements: {
          Fire: 4,
          Water: 8,
          Mirage: 5,
        },
        fulfilledShardSkills: [
          30,
          34,
          36,
          46,
        ],
      },
      driveLine: {
        slots: [
          41,
          82,
          107,
          73,
        ],
        elements: {
          Fire: 6,
          Time: 9,
          Space: 14,
          Earth: 10,
        },
        fulfilledShardSkills: [
          58,
          63,
          67,
          68,
          73,
          74,
          83,
        ],
      },
      extraLine: {
        slots: [
          38,
          21,
          70,
        ],
        elements: {
          Fire: 6,
          Water: 2,
          Wind: 6,
          Space: 4,
        },
        fulfilledShardSkills: [
          86,
          87,
          89,
          103,
          108,
        ],
      },
    },
    {
      weaponLine: {
        slots: [
          61,
          97,
          112,
          124,
        ],
        elements: {
          Wind: 7,
          Mirage: 10,
          Space: 6,
        },
        fulfilledShardSkills: [
          3,
          5,
          13,
          19,
          26,
        ],
      },
      shieldLine: {
        slots: [
          40,
          30,
          -1,
          122,
        ],
        elements: {
          Fire: 4,
          Water: 8,
          Mirage: 5,
        },
        fulfilledShardSkills: [
          30,
          34,
          36,
          46,
        ],
      },
      driveLine: {
        slots: [
          41,
          82,
          107,
          73,
        ],
        elements: {
          Fire: 6,
          Time: 9,
          Space: 14,
          Earth: 10,
        },
        fulfilledShardSkills: [
          58,
          63,
          67,
          68,
          73,
          74,
          83,
        ],
      },
      extraLine: {
        slots: [
          38,
          21,
          70,
        ],
        elements: {
          Fire: 6,
          Water: 2,
          Wind: 6,
          Space: 4,
        },
        fulfilledShardSkills: [
          86,
          87,
          89,
          103,
          108,
        ],
      },
    },
    {
      weaponLine: {
        slots: [
          123,
          97,
          112,
          124,
        ],
        elements: {
          Mirage: 15,
          Earth: 3,
          Wind: 4,
          Space: 6,
        },
        fulfilledShardSkills: [
          0,
          3,
          5,
          13,
          19,
        ],
      },
      shieldLine: {
        slots: [
          40,
          30,
          -1,
          122,
        ],
        elements: {
          Fire: 4,
          Water: 8,
          Mirage: 5,
        },
        fulfilledShardSkills: [
          30,
          34,
          36,
          46,
        ],
      },
      driveLine: {
        slots: [
          41,
          82,
          107,
          73,
        ],
        elements: {
          Fire: 6,
          Time: 9,
          Space: 14,
          Earth: 10,
        },
        fulfilledShardSkills: [
          58,
          63,
          67,
          68,
          73,
          74,
          83,
        ],
      },
      extraLine: {
        slots: [
          38,
          21,
          70,
        ],
        elements: {
          Fire: 6,
          Water: 2,
          Wind: 6,
          Space: 4,
        },
        fulfilledShardSkills: [
          86,
          87,
          89,
          103,
          108,
        ],
      },
    },
    {
      weaponLine: {
        slots: [
          123,
          97,
          6,
          124,
        ],
        elements: {
          Mirage: 11,
          Earth: 11,
          Wind: 4,
          Space: 6,
        },
        fulfilledShardSkills: [
          3,
          5,
          7,
          13,
          19,
        ],
      },
      shieldLine: {
        slots: [
          40,
          30,
          -1,
          122,
        ],
        elements: {
          Fire: 4,
          Water: 8,
          Mirage: 5,
        },
        fulfilledShardSkills: [
          30,
          34,
          36,
          46,
        ],
      },
      driveLine: {
        slots: [
          41,
          82,
          107,
          73,
        ],
        elements: {
          Fire: 6,
          Time: 9,
          Space: 14,
          Earth: 10,
        },
        fulfilledShardSkills: [
          58,
          63,
          67,
          68,
          73,
          74,
          83,
        ],
      },
      extraLine: {
        slots: [
          38,
          21,
          70,
        ],
        elements: {
          Fire: 6,
          Water: 2,
          Wind: 6,
          Space: 4,
        },
        fulfilledShardSkills: [
          86,
          87,
          89,
          103,
          108,
        ],
      },
    },
    {
      weaponLine: {
        slots: [
          123,
          97,
          6,
          124,
        ],
        elements: {
          Mirage: 11,
          Earth: 11,
          Wind: 4,
          Space: 6,
        },
        fulfilledShardSkills: [
          3,
          5,
          7,
          13,
          19,
        ],
      },
      shieldLine: {
        slots: [
          40,
          30,
          -1,
          122,
        ],
        elements: {
          Fire: 4,
          Water: 8,
          Mirage: 5,
        },
        fulfilledShardSkills: [
          30,
          34,
          36,
          46,
        ],
      },
      driveLine: {
        slots: [
          41,
          76,
          107,
          73,
        ],
        elements: {
          Fire: 6,
          Time: 8,
          Space: 14,
          Earth: 10,
        },
        fulfilledShardSkills: [
          58,
          63,
          67,
          68,
          73,
          74,
          83,
        ],
      },
      extraLine: {
        slots: [
          38,
          21,
          70,
        ],
        elements: {
          Fire: 6,
          Water: 2,
          Wind: 6,
          Space: 4,
        },
        fulfilledShardSkills: [
          86,
          87,
          89,
          103,
          108,
        ],
      },
    },
    {
      weaponLine: {
        slots: [
          53,
          97,
          6,
          124,
        ],
        elements: {
          Fire: 7,
          Mirage: 11,
          Earth: 8,
          Wind: 4,
          Space: 6,
        },
        fulfilledShardSkills: [
          2,
          3,
          5,
          7,
          13,
          14,
          19,
        ],
      },
      shieldLine: {
        slots: [
          40,
          30,
          -1,
          122,
        ],
        elements: {
          Fire: 4,
          Water: 8,
          Mirage: 5,
        },
        fulfilledShardSkills: [
          30,
          34,
          36,
          46,
        ],
      },
      driveLine: {
        slots: [
          41,
          76,
          107,
          73,
        ],
        elements: {
          Fire: 6,
          Time: 8,
          Space: 14,
          Earth: 10,
        },
        fulfilledShardSkills: [
          58,
          63,
          67,
          68,
          73,
          74,
          83,
        ],
      },
      extraLine: {
        slots: [
          38,
          21,
          70,
        ],
        elements: {
          Fire: 6,
          Water: 2,
          Wind: 6,
          Space: 4,
        },
        fulfilledShardSkills: [
          86,
          87,
          89,
          103,
          108,
        ],
      },
    },
    {
      weaponLine: {
        slots: [
          53,
          97,
          6,
          124,
        ],
        elements: {
          Fire: 7,
          Mirage: 11,
          Earth: 8,
          Wind: 4,
          Space: 6,
        },
        fulfilledShardSkills: [
          2,
          3,
          5,
          7,
          13,
          14,
          19,
        ],
      },
      shieldLine: {
        slots: [
          40,
          30,
          -1,
          122,
        ],
        elements: {
          Fire: 4,
          Water: 8,
          Mirage: 5,
        },
        fulfilledShardSkills: [
          30,
          34,
          36,
          46,
        ],
      },
      driveLine: {
        slots: [
          41,
          76,
          107,
          28,
        ],
        elements: {
          Fire: 6,
          Time: 4,
          Water: 5,
          Space: 14,
          Earth: 10,
        },
        fulfilledShardSkills: [
          57,
          58,
          60,
          63,
          68,
          73,
          74,
          83,
        ],
      },
      extraLine: {
        slots: [
          38,
          21,
          70,
        ],
        elements: {
          Fire: 6,
          Water: 2,
          Wind: 6,
          Space: 4,
        },
        fulfilledShardSkills: [
          86,
          87,
          89,
          103,
          108,
        ],
      },
    },
    {
      weaponLine: {
        slots: [
          53,
          97,
          6,
          124,
        ],
        elements: {
          Fire: 7,
          Mirage: 11,
          Earth: 8,
          Wind: 4,
          Space: 6,
        },
        fulfilledShardSkills: [
          2,
          3,
          5,
          7,
          13,
          14,
          19,
        ],
      },
      shieldLine: {
        slots: [
          40,
          30,
          -1,
          122,
        ],
        elements: {
          Fire: 4,
          Water: 8,
          Mirage: 5,
        },
        fulfilledShardSkills: [
          30,
          34,
          36,
          46,
        ],
      },
      driveLine: {
        slots: [
          41,
          117,
          107,
          28,
        ],
        elements: {
          Fire: 6,
          Mirage: 3,
          Water: 5,
          Space: 14,
          Earth: 10,
        },
        fulfilledShardSkills: [
          57,
          58,
          62,
          63,
          68,
          73,
          83,
        ],
      },
      extraLine: {
        slots: [
          38,
          21,
          70,
        ],
        elements: {
          Fire: 6,
          Water: 2,
          Wind: 6,
          Space: 4,
        },
        fulfilledShardSkills: [
          86,
          87,
          89,
          103,
          108,
        ],
      },
    },
    {
      weaponLine: {
        slots: [
          53,
          97,
          78,
          124,
        ],
        elements: {
          Fire: 7,
          Mirage: 11,
          Time: 8,
          Wind: 4,
          Space: 6,
        },
        fulfilledShardSkills: [
          2,
          3,
          5,
          11,
          13,
          14,
          19,
        ],
      },
      shieldLine: {
        slots: [
          40,
          30,
          -1,
          122,
        ],
        elements: {
          Fire: 4,
          Water: 8,
          Mirage: 5,
        },
        fulfilledShardSkills: [
          30,
          34,
          36,
          46,
        ],
      },
      driveLine: {
        slots: [
          41,
          117,
          107,
          28,
        ],
        elements: {
          Fire: 6,
          Mirage: 3,
          Water: 5,
          Space: 14,
          Earth: 10,
        },
        fulfilledShardSkills: [
          57,
          58,
          62,
          63,
          68,
          73,
          83,
        ],
      },
      extraLine: {
        slots: [
          38,
          21,
          70,
        ],
        elements: {
          Fire: 6,
          Water: 2,
          Wind: 6,
          Space: 4,
        },
        fulfilledShardSkills: [
          86,
          87,
          89,
          103,
          108,
        ],
      },
    },
    {
      weaponLine: {
        slots: [
          53,
          97,
          78,
          124,
        ],
        elements: {
          Fire: 7,
          Mirage: 11,
          Time: 8,
          Wind: 4,
          Space: 6,
        },
        fulfilledShardSkills: [
          2,
          3,
          5,
          11,
          13,
          14,
          19,
        ],
      },
      shieldLine: {
        slots: [
          40,
          30,
          -1,
          122,
        ],
        elements: {
          Fire: 4,
          Water: 8,
          Mirage: 5,
        },
        fulfilledShardSkills: [
          30,
          34,
          36,
          46,
        ],
      },
      driveLine: {
        slots: [
          41,
          117,
          107,
          28,
        ],
        elements: {
          Fire: 6,
          Mirage: 3,
          Water: 5,
          Space: 14,
          Earth: 10,
        },
        fulfilledShardSkills: [
          57,
          58,
          62,
          63,
          68,
          73,
          83,
        ],
      },
      extraLine: {
        slots: [
          38,
          21,
          98,
        ],
        elements: {
          Fire: 6,
          Water: 2,
          Space: 5,
        },
        fulfilledShardSkills: [
          86,
          89,
          103,
        ],
      },
    },
    {
      weaponLine: {
        slots: [
          53,
          97,
          78,
          124,
        ],
        elements: {
          Fire: 7,
          Mirage: 11,
          Time: 8,
          Wind: 4,
          Space: 6,
        },
        fulfilledShardSkills: [
          2,
          3,
          5,
          11,
          13,
          14,
          19,
        ],
      },
      shieldLine: {
        slots: [
          40,
          30,
          -1,
          122,
        ],
        elements: {
          Fire: 4,
          Water: 8,
          Mirage: 5,
        },
        fulfilledShardSkills: [
          30,
          34,
          36,
          46,
        ],
      },
      driveLine: {
        slots: [
          41,
          20,
          107,
          28,
        ],
        elements: {
          Fire: 6,
          Water: 11,
          Space: 14,
          Earth: 10,
        },
        fulfilledShardSkills: [
          58,
          63,
          64,
          68,
          73,
          80,
          83,
        ],
      },
      extraLine: {
        slots: [
          38,
          21,
          98,
        ],
        elements: {
          Fire: 6,
          Water: 2,
          Space: 5,
        },
        fulfilledShardSkills: [
          86,
          89,
          103,
        ],
      },
    },
  ],
  bestScore: 59,
}
